#  ┏┓┏┓┏┓┏┳┓┳┏┓┓┏  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┗┓┃┃┃┃ ┃ ┃┣ ┗┫━━┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┗┛┣┛┗┛ ┻ ┻┻ ┗┛  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                                  


[Comfy]
text               = dfe3e7
subtext            = c0c7cd
main               = 0f1417
main-elevated      = 353a3d
main-transition    = 0a0f12
highlight          = 171c1f
highlight-elevated = 313539
sidebar            = 0f1417
player             = 000000
card               = 000000
shadow             = 000000
selected-row       = dfe3e7
button             = 8fcff3
button-active      = c3e8ff
button-disabled    = 8fcff3
tab-active         = 0f1417
notification       = c9c1ea
notification-error = ffb4ab
misc               = 000000
play-button        = b5c9d7
play-button-active = d1e5f4
progress-fg        = 8fcff3
progress-bg        = 0f1417
heart              = ffb4ab
pagelink-active    = e6deff
radio-btn-active   = e6deff
