#  ┏┓┏┓┏┓┏┳┓┳┏┓┓┏  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┗┓┃┃┃┃ ┃ ┃┣ ┗┫━━┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┗┛┣┛┗┛ ┻ ┻┻ ┗┛  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                                  


[Comfy]
text               = e0e3e8
subtext            = c1c7ce
main               = 101417
main-elevated      = 363a3e
main-transition    = 0b0f12
highlight          = 181c20
highlight-elevated = 313539
sidebar            = 101417
player             = 000000
card               = 000000
shadow             = 000000
selected-row       = e0e3e8
button             = 96ccf8
button-active      = cae6ff
button-disabled    = 96ccf8
tab-active         = 101417
notification       = d0c0e8
notification-error = ffb4ab
misc               = 000000
play-button        = b7c9d9
play-button-active = d3e5f6
progress-fg        = 96ccf8
progress-bg        = 101417
heart              = ffb4ab
pagelink-active    = ebdcff
radio-btn-active   = ebdcff
