-- plugins/conform.lua
-- return {
--   "stevearc/conform.nvim", -- plugin name
--   config = function()
--     require("conform").setup({
--       formatters_by_ft = {
--         lua = { "stylua" },
--         python = { "black" },
--         sh = { "shfmt" },
--       },
--     })
--   end,
-- }
